mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("blog.url", namespace="blog"))
]

blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone


class PostManager(models.Manager):
    def y(self, year):
        return self.filter(publish__year=year)


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status="published")


class Post(models.Model):
    STATUS_CHOICES = (
        ("draft", "Draft"),
        ("published", "Published")
    )
    title = models.CharField(max_length=60)
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name="blog_post")
    body = models.TextField()
    status = models.CharField(max_length=10,
                              choices=STATUS_CHOICES,
                              default="Draft")
    publish = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(max_length=250)

    objects = PostManager()
    published = PublishedManager()

    def get_absolute_url(self):
        return reverse("blog:post_detail",
                       args=[self.slug, self.pk])

    def __str__(self):
        return self.title


class Account(models.Model):
    GENDER_CHOICES = (
        ("آقا", "آقا"),
        ("خانم", "خانم")
    )
    user = models.OneToOneField(User,
                                on_delete=models.CASCADE,
                                related_name="account")
    phone = models.CharField(max_length=11)
    gender = models.CharField(max_length=11,
                              choices=GENDER_CHOICES,
                              default="خانم")
    address = models.TextField(null=True, blank=True)

    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    age = models.PositiveIntegerField(default=0,
                                      null=True, blank=True)

    objects = models.Manager()

    def __str__(self):
        return self.user.first_name + " " + self.user.last_name

blog/forms.py
from .models import Account
from django import forms


# class AccountForm(forms.ModelForm):
#     class Meta:
#         model = Account
#         fields = ("gender", "address")


class AccountForm(forms.Form):
    GENDER_CHOICES = (
        ("آقا", "آقا"),
        ("خانم", "خانم")
    )
    phone = forms.CharField(max_length=11, required=True)
    gender = forms.ChoiceField(choices=GENDER_CHOICES,
                               required=True,
                               widget=forms.RadioSelect,
                               label='جنسیت')
    address = forms.CharField(widget=forms.Textarea,
                              max_length=250,
                              label='آدرس')
    first_name = forms.CharField(max_length=30,
                                 label='نام ',
                                 help_text=" نام را وارد کنید ",
                                 required=False)
    last_name = forms.CharField(max_length=11,
                                label='نام خانوادگی')
    age = forms.IntegerField(label='سن')

    def clean_first_name(self):
        n = self.cleaned_data["first_name"]
        if len(n) < 5:
            return n
        else:
            raise forms.ValidationError("تعداد کاراکتر نام بیشتر از ۵ است")

    def clean_phone(self):
        phone = self.cleaned_data["phone"]
        if phone:
            if not phone.isnumeric():
                raise forms.ValidationError("شماره تلفن باید عددی باشد")
            else:
                return phone

    def clean_age(self):
        v = self.cleaned_data["age"]
        if v:
            if v < 0:
                return v
            else:
                return forms.ValidationError("تعداد ارقام سن نباید منفی باشد ")

blog/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView
from .forms import AccountForm
from .models import Post, Account


def index(request):
    return HttpResponse("hi")


# def post_list(request):
#     # ol = get_object_or_404(Post) # فقط برای تک آبجکت بکار می‌رود
#     # ol = Post.published.all()
#     # ol = Post.objects.y(2020)
#     # ol = Post.objects.filter(publish__year="2024")
#     # ol = Post.objects.filter(status="published")
#     ol = Post.objects.all()
#
#     pagination = Paginator(ol, 2)
#     page = request.GET.get("page")
#
#     try:
#         posts = pagination.page(page)
#     except EmptyPage:
#         posts = pagination.page(1)
#     except PageNotAnInteger:
#         posts = pagination.page(pagination.num_pages)
#
#     return render(request,
#                   "post/post_list.html",
#                   {"posts": posts})


class PostListView(ListView):
    queryset = Post.objects.all()
    context_object_name = "posts"
    paginate_by = 2
    template_name = "post/post_list.html"


def post_detail(request, pk, slug):
    # post = Post.objects.get(pk=pk, slug=slug)
    post = get_object_or_404(Post, pk=pk, slug=slug)
    return render(request,
                  "post/post_detail.html",
                  {"post": post})


def account_form(request, *args, **kwargs):
    user = request.user
    # account = kwargs.get(pk=user)
    try:
        account = Account.objects.get(user=user)
    except:
        account = Account.objects.create(user=user)

    if not user.is_authenticated:
        return redirect("blog:index")

    if request.method == "POST":
        form = AccountForm(data=request.POST)
        if form.is_valid():

            cd = form.cleaned_data

            account.gender = cd["gender"]
            account.address = cd["address"]
            account.age = cd["age"]
            account.phone = cd["phone"]

            user.first_name = cd["first_name"]
            user.last_name = cd["last_name"]

            user.save()
            account.save()

            return redirect("/")

    else:
        form = AccountForm(initial={
            "first_name": account.user.first_name,
            "last_name": account.user.last_name,
            "phone": account.phone,
            "address": account.address,
            "age": account.age,
        })

    return render(request,
                  "forms/account_form.html",
                  {"form": form,
                   "account": account})

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> {% block title %} {% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/list.css' %}">
</head>
<body>

{% include 'partial/header.html' %}
{% include 'partial/navBar.html' %}

{% block content %}

{% endblock %}

{% include 'partial/footer.html' %}
</body>
</html>

templates/forms/account_form.html
{% extends 'base.html' %}

{% block content %}
<h1 style="color: blue"> فرم اطلاعات </h1>


<form action="" method="post">
    {% csrf_token %}
{% if form.errors %}
    <p style="color:red">
        لظفا خطاهای ۱ زیر را اصلاح کنید
        <br>
    </p>
    {{ form.errors }}

{% elif orm.management_form %}
    <p style="color:red">
        لظفا خطاهای ۲ زیر را اصلاح کنید
        <br>
    </p>
    {{ form.management_form }}

{% elif form.non_field_errors %}
    <p style="color:red">
        لظفا خطاهای ۳ زیر را اصلاح کنید
        <br>
    </p>
    {{ form.non_field_errors }}

{% elif form.non_form_errors %}
    <p style="color:red">
        لظفا خطاهای ۴ زیر را اصلاح کنید
        <br>
    </p>
    {{ form.non_form_errors }}

{% endif %}

<br>
<hr>

    <div>
        <label >
            <input type="text"
                   name="first_name"
                   id="id_first_name"
                   maxlength="30"
                   {% if form.first_name.value %}
                    value="{{ form.first_name.value }}"
                   {% else %}
                    value="{{ account.user.first_name }}"
                   {% endif %}
            >
        Username</label>
    </div>
    <hr>
    <br>

    <div>
        <label >نام خانوادگی </label>
        {{ form.last_name }}
    </div>
    <hr>
    <br>

    <div>
        <label  disabled="True">phone </label>
        {{ form.phone }}
    </div>
    <hr>
    <br>

    <div>
        <label  >age  </label>
        {{ form.age }}
    </div>
    <hr>
    <br>

    <div>
        <label >gender </label>
        {{ form.gender }}
    </div>
    <hr>
    <br>

    <div>
        <label  >address </label>
        {{ form.address }}
    </div>
    <hr>
    <br>

    <button type="submit"> ثبت نام </button>
</form>


{% endblock %}

templates/partial/pagination.html
<div>
    <span>
        {% if posts.has_previous %}
            <a href="?page={{posts.previous_page_number}} "> صفحه قبل </a>
        {% endif %}
    </span>

    <span>
        Page {{ posts.number }} of {{ posts.paginator.num_pages }}
    </span>

    <span>
        {% if posts.has_next %}
            <a href="?page={{posts.next_page_number}}"> صفحه بعد </a>
        {% endif %}
    </span>

    <br>

    <span>
        {% for i  in posts.paginator.page_range %}
            {% if i == posts.number %}
                <span style="color:red">{{ i }}</span>
            {% else %}
                {{ i }}
            {% endif %}
        {% endfor %}
    </span>

</div>


{% if post.has_next %}
aaaa
{% endif %}

templates/post/post_detail.html
{% extends 'base.html' %}

{% block title %} detail {% endblock %}

{% block content %}
{{ post.body }}
{% endblock %}

templates/post/post_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %} list {% endblock %}

{% block head %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/list.css' %}">
{% endblock %}

{% block content %}
<h1> لیست پست‌ها </h1>
<ul>
    {% for post in posts %}
        <li>
            <h2>
                <a href="{% url 'blog:post_detail' pk=post.pk slug=post.slug %}">
                    {{ post.title }}
                </a>
            </h2>
            <h4 class="test">
                {{ post.body }}
            </h4>

        </li>
    {% endfor %}

    {% include 'partial/pagination.html' with posts=page_obj%}
</ul>

{% endblock %}